Repository Strivacity/integrations, pull requests merged in 2022-03, with the labels that each got.

#4 add discord integration
  hooks/discord/post-account-login.hook.js
Labels: PR: reviewed-approved, size/M

#7 add deduce integration
  hooks/deduce/pre-registration.hook.js
Labels: size/L, PR: reviewed-approved

#8 fix filter group for hubspot query
  hooks/hubspot/pre-registration.hook.js
Labels: PR: reviewed-approved, size/XS

#10 add missing helper code
  hooks/hubspot/pre-registration.hook.js
Labels: PR: reviewed-approved, size/M

#13 fix badge url
  README.md
Labels: PR: reviewed-approved, size/XS

#14 use gh badge
  README.md
Labels: PR: reviewed-approved, size/XS

#15 add gitignore
  .gitignore
Labels: PR: reviewed-approved, size/XS

#9 Add eventbridge integration
  hooks/eventbridge/pre-registration.hook.js
Labels: size/L, PR: reviewed-approved

#17 trigger actions on PRs
  .github/workflows/main.yml
Labels: PR: reviewed-approved, size/XS

#16 fix linter errors
  .eslintrc.json
  hooks/iddataweb/pre-registration.hook.js
  hooks/salesforce/pre-registration.hook.js
  hooks/seczetta/post-identification.hook.js
Labels: PR: reviewed-approved, size/M

#18 update readme
  README.md
Labels: PR: reviewed-approved, size/M

#19 clean all lint warnings
  .eslintrc.json
  hooks/seczetta/post-identification.hook.js
Labels: PR: reviewed-approved, size/XS
